version: '3.8'
services:
  db:
    image: yobasystems/alpine-mariadb:latest
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress_data:/var/www/html
    ports:
      - "2222:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_password

volumes:
  mysql_data:
    driver: local
  wordpress_data:
    driver: local
